apiVersion: v1
kind: Secret
metadata:
  name: registrypullsecretgarraboscariou
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOiB7CgkJCSJhdXRoIjogIloyRnljbUZpYjNOallYSnBiM1U2UjJGeWNtRmlRMkZ5SlE9PSIKCQl9Cgl9Cn0=
type: kubernetes.io/dockerconfigjson