apiVersion: v1
kind: Service
metadata:
  name: ml-sentiment-analysis-service
  labels:
    app: my-api-sentiment-analysis
spec:
  type: ClusterIP
  ports:
  - port: 8001
    protocol: TCP
    targetPort: 8000
  selector:
    app: my-api-sentiment-analysis
