apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-sentiment-analysis-deployment
  labels:
    app: my-api-sentiment-analysis
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-api-sentiment-analysis
  template:
    metadata:
      labels:
        app: my-api-sentiment-analysis
    spec:
      containers:
      - name: my-api-sentiment-analysis
        image: garraboscariou/ml-api-sentiment-analysis:v1.0.0
        ports:
        - containerPort: 8000
      imagePullSecrets:
      - name: registrypullsecretgarraboscariou